name: open-problems-23-sc-perturbation-prediction

dependencies:
  - anndata=0.10.6
  - matplotlib==3.7.1
  - mudata==0.2.3
  - muon==0.1.6
  - numpy=1.26.4
  - pandas=2.2.1
  - pip==23.3.1
  - pyyaml=6.0.1
  - scanpy=1.10.1
  - scikit-learn=1.2.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - pip:
    - celltypist==1.6.2
  